apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ template "conanexiles.fullname" . }}
  labels:
    gamename: "{{ .Values.deploymentLabels.gameName }}"
    custguild: "{{ .Values.deploymentLabels.customerGuildID }}"
    app: {{ template "conanexiles.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ template "conanexiles.fullname" . }}
      release: "{{ .Release.Name }}"
  template:
    metadata:
      labels:
        app: {{ template "conanexiles.fullname" . }}
        release: "{{ .Release.Name }}"
    spec:
      containers:
      - name: {{ template "conanexiles.fullname" . }}
        image: "{{ .Values.image }}:{{ .Values.imageTag }}"
        imagePullPolicy: Always
        
        {{ if .Values.env }}
        env:
{{ toYaml .Values.env | indent 10 }}
        {{- end }}
        
        resources:
{{ toYaml .Values.resources | indent 10 }}

        ports:
        - name: conanexiles-1
          containerPort: 7777
          protocol: UDP
        - name: conanexiles-2
          containerPort: 7778
          protocol: UDP
        - name: conanexiles-3
          containerPort: 27015
          protocol: UDP
        volumeMounts:
        - name: config
          mountPath: /conanexiles
      volumes:
      - name: config
        persistentVolumeClaim:
{{- if eq .Values.persistence.claimName "" }}
          claimName: {{ template "conanexiles.fullname" . }}-config
{{- else }}
          claimName: {{ .Values.persistence.claimName }}
{{- end }}
